# -*- mode: ruby -*-
# # vi: set ft=ruby :

require 'fileutils'

CONFIG = File.join(File.dirname(__FILE__), "../config.rb")
require CONFIG

$num_instances = $num_web_instances

VAGRANT = File.join(File.dirname(__FILE__), "../vagrant.rb")
require VAGRANT